### ISSUE TITLE
Unexpected error when accessing not-found pages with filesystemRoutingRoot config

### ISSUE THREAD

**Issue by luisfloat** [vikejs/vike#1183]
### Description

I encountered a bug while working with Vike in development mode, specifically when trying to access not-found pages using the `filesystemRoutingRoot` config. It's crucial to highlight that this issue only appears during development, not in the built version of the application.

## Steps to Reproduce

1. Set up `file-structure-domain-driven-v1` example:

```bash
git clone https://github.com/vikejs/vike
cd vike/examples/file-structure-domain-driven-v1/
npm install
npm run dev
```

2. Attempt to access a non-existent page (e.g., /profile).

## Expected Behavior

In a typical development environment, the Vike should handle routing to not-found pages seamlessly, even when the `filesystemRoutingRoot` config is utilized.

## Actual Behavior

The bug leads to improper routing and fails to display the expected not-found page when navigating to non-existent routes. This behavior is specific to the development mode and does not affect the built version of the application.

## Additional Information

Bug Manifestation:

```bash
at /node_modules/vike/dist/esm/node/runtime/renderPage/log404/index.js:83:9
    at Array.forEach (<anonymous>)
    at getPagesAndRoutesInfo (/node_modules/vike/dist/esm/node/runtime/renderPage/log404/index.js:74:18)
    at log404 (/node_modules/vike/dist/esm/node/runtime/renderPage/log404/index.js:18:13)
    at renderPageAlreadyPrepared (/node_modules/vike/dist/esm/node/runtime/renderPage.js:128:15)
    at renderPageAndPrepare (/node_modules/vike/dist/esm/node/runtime/renderPage.js:93:12)
    at /node_modules/vike/dist/esm/node/plugin/shared/getHttpRequestAsyncStore.js:68:35
    at renderPage (/node_modules/vike/dist/esm/node/runtime/renderPage.js:46:50)
    at /node_modules/vike/dist/esm/node/plugin/shared/addSsrMiddleware.js:18:27
```

Node Version: v20.7.0
NPM Version: v10.1.0

---

This issue can cause hindrances during the development process, and it will be nice to address it to ensure a smooth development experience with Vike.

**Comment by brillout** [comment]
I tried to reproduce but couldn't: https://github.com/brillout/vike-reprod-1183.

**Comment by brillout** [comment]
(I noticed the 404 table layout is broken, which I just fixed.)

**Comment by luisfloat** [comment]
> I tried to reproduce but couldn't: https://github.com/brillout/vike-reprod-1183.

Unfortunately, I'm still getting the same errors as detailed in my initial report. However, I've observed an interesting behavior: when accessing /about.html, the error page is displayed correctly, even though the corresponding route indirectly points to /about. On the other hand, when attempting to access actually not-found pages like /profile, it triggers an error in the terminal, and the page isn't rendered correctly.

> (I noticed the 404 table layout is broken, which I just fixed.)

Thank you for your efforts in trying to reproduce the issue and for fixing the 404 table layout.

**Comment by luisfloat** [comment]
I've made another observation worth mentioning. The error seems to only occur when using the V1 Design, but when switching to the older design, it functions correctly.

**Comment by brillout** [comment]
I've done some digging around the stack trace you provided and I can't think of reason why you get that error.

The best would be a reproduction.

**Comment by brillout** [comment]
(Or try `vike@0.4.143-commit-dc6fea`.)

**Comment by brillout** [comment]
I made some changes related to the code that fails. You can try `vike@0.4.143-commit-fa295e1` and see if it works. If you still get the error, then the best would be a reproduction.

Closing in the meantime, I'll re-open if I get a reproduction.

**Comment by vivazzi** [comment]
I tryied vike=0.4.144 and it helps me. Thank you for awesome vike!
