### ISSUE TITLE
Client Side Routing Errors If Query Does Not Begin with Path in Link's href Attribute

### ISSUE THREAD

**Issue by kcoet** [vikejs/vike#1281]
### Description

First of all, thank you for the amazing library, I hope it continues to grow.

Client-side routing will generate an error if the href in the link does not begin with a path like the following: `?q=any`

Works fine if the link starts with a path like this: `/?q=any`

Here is the error message.

```
Uncaught (in promise) Error: [vike@0.4.147][Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at createErrorWithCleanStackTrace (createErrorWithCleanStackTrace.js?v=31c18431:8:15)
    at assert (assert.js?v=31c18431:52:27)
    at assertPathname (parseUrl.js?v=31c18431:179:5)
    at analyzeBaseServer (parseUrl.js?v=31c18431:183:5)
    at parseUrl (parseUrl.js?v=31c18431:65:39)
    at hasBaseServer (skipLink.js?v=31c18431:56:31)
    at skipLink (skipLink.js?v=31c18431:16:10)
    at prefetch.js?v=31c18431:72:13
    at Array.forEach (<anonymous>)
    at addLinkPrefetchHandlers (prefetch.js?v=31c18431:67:14)
    at renderPageClientSide.js?v=31c18431:234:9
    at async renderPageClientSide (renderPageClientSide.js?v=31c18431:237:5)
createErrorWithCleanStackTrace @ createErrorWithCleanStackTrace.js?v=31c18431:8
assert @ assert.js?v=31c18431:52
assertPathname @ parseUrl.js?v=31c18431:179
analyzeBaseServer @ parseUrl.js?v=31c18431:183
parseUrl @ parseUrl.js?v=31c18431:65
hasBaseServer @ skipLink.js?v=31c18431:56
skipLink @ skipLink.js?v=31c18431:16
(anonymous) @ prefetch.js?v=31c18431:72
addLinkPrefetchHandlers @ prefetch.js?v=31c18431:67
(anonymous) @ renderPageClientSide.js?v=31c18431:234
await in (anonymous) (async)
installClientRouter @ installClientRouter.js?v=31c18431:16
(anonymous) @ entry.js:9
```
Demo: https://stackblitz.com/edit/stackblitz-starters-uet6jt?file=pages%2Findex%2Findex.page.tsx

![image](https://github.com/vikejs/vike/assets/110478020/51d4e711-fd24-44a0-8c7f-736c74dc8c9f)

---

Additionally, pageContext.urlParsed is also missing the type.

**Comment by brillout** [comment]
Thanks for the bug report, I'll have a look at it. In the meantime use `/?q=any` instead of `?q=any`.

> pageContext.urlParsed is also missing the type

What do you mean?

**Comment by brillout** [comment]
Fixed. Let me know if you need the fix released.

> First of all, thank you for the amazing library, I hope it continues to grow.

I'm gad you like it. Would [sponsoring](https://github.com/sponsors/vikejs) be an option for your company? For Vike to grow we need the help of companies 🙂

**Comment by kcoet** [comment]
> Fixed. Let me know if you need the fix released.

I have checked it and it works fine, waiting for the release.

> I'm gad you like it. Would [sponsoring](https://github.com/sponsors/vikejs) be an option for your company? For Vike to grow we need the help of companies 🙂

I will notify my company.

> > pageContext.urlParsed is also missing the type
> 
> What do you mean?

I mean the Typescript type for `pagecontext.urlParsed` is not resolved properly (missing).

![image](https://github.com/vikejs/vike/assets/110478020/47cce99a-8da1-46d7-a24e-5d14930474db)

**Comment by AurelienLourot** [comment]
> I mean the Typescript type for `pagecontext.urlParsed` is not resolved properly (missing).

Strange, things are fine in `examples/react-full-v1`:

![Screenshot from 2023-11-24 11-31-15](https://github.com/vikejs/vike/assets/11795312/941cf5f9-78e2-40ec-95a3-df49b4f5e659)

Is the implementation of `usePageContext()` maybe different in your project?

**Comment by AurelienLourot** [comment]
Note that this is hidden on the screenshot but I slightly modified `Link.tsx` in order to achieve this:

```diff
 function Link({ href, children }: { href: string; children: string }) {
-  const pageContext = usePageContext() as { urlPathname: string } // TODO
+  const pageContext = usePageContext()
+  console.log(pageContext.urlParsed)
   const { urlPathname } = pageContext
```

**Comment by brillout** [comment]
> I will notify my company.

🙏 Let us know how it goes, also if it's a no.
