### ISSUE TITLE
[vike@0.4.201][Bug] You stumbled upon a Vike bug. 

### ISSUE THREAD

**Issue by Plajer** [vikejs/vike#1962]
### Description
Received such error via Sentry

![Firefox_Screenshot_2024-11-16T23-41-19 610Z](https://github.com/user-attachments/assets/9c5cadd4-6f7e-488b-b570-44febbc85a3c)

No more context available.

**Comment by brillout** [comment]
Are you, or one of your libraries, using `history.pushState()` or `history.replaceState()`?

**Comment by Plajer** [comment]
Maybe [Swiper.js](https://swiperjs.com/) does such things under the hood. It is used to display swipeable cards linking to other pages. If so should I seek to override to change the logic to something else?

**Comment by brillout** [comment]
Any `history.pushState()`/`history.replaceState()` call should called after [Vike monkey patches both](https://github.com/vikejs/vike/blob/eb15395903f2a0d5494a49a60792d356129a7dd1/vike/client/client-routing-runtime/history.ts#L116).

Keep us updated. At least the error message should be improved.

**Comment by Plajer** [comment]
I've created repository based on sample Vike page at the repository here https://github.com/Plajer/vike-issue-1962

The issue is located in [pages/star-wards/index/+Page.tsx](https://github.com/Plajer/vike-issue-1962/blob/d1f5afe286915185c88f6add93a893107035c197/pages/star-wars/index/%2BPage.tsx#L10)

When `Vike issue test` anchor pointing towards # is clicked and scroll is done through page (made 200vh on div to do so) the error appears.

The issue wasn't related to external libraries using history API.

**Comment by brillout** [comment]
Can you make the repo public? I get a 404.

**Comment by Plajer** [comment]
Pardon, it's public now.

**Comment by brillout** [comment]
> When `Vike issue test` anchor pointing towards # is clicked and scroll is done through page (made 200vh on div to do so) the error appears.

I cannot reproduce. What steps exactly lead to the error?

**Comment by brillout** [comment]
Actually, it seems to be a race condition and I think I found what causes it. I pushed a fix and pre-released it as `0.4.203-commit-d47722f`. Let me know if you still get the error (if you do I'll re-open).

**Comment by brillout** [comment]
Use `0.4.203-commit-1b14559` (the previous pre-release contained a regression).

**Comment by Plajer** [comment]
I still do have the error in version `vike@0.4.203-commit-1b14559`.

```
[vike@0.4.203-commit-1b14559][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    createErrorWithCleanStackTrace createErrorWithCleanStackTrace.js:4
    assert assert.js:54
    getState history.js:52
    saveScrollPosition history.js:68
    onPageHide onPageVisibilityChange.js:6
    onPageHide onPageVisibilityChange.js:4
    autoSaveScrollPosition setScrollPosition.js:76
    initHistoryAndScroll initClientRouter.js:34
    initClientRouter initClientRouter.js:12
    <anonymous> entry.js:10
```

**Comment by Plajer** [comment]
Worth noting that this issue doesn't occur at Chrome 131 but does on Firefox 131.

**Comment by brillout** [comment]
Fix released in `0.4.204`.

**Comment by brillout** [comment]
Did you remove Vite's cache `rm -r node_modules/.vite`?

**Comment by Plajer** [comment]
Can confirm having latest version. Works well on Firefox 131 but issue persists on Firefox Developer Edition 133.0b9 but not every page refresh, might be an issue or regression of a beta preview then.

**Comment by brillout** [comment]
I assume it's a separate issue so having an error stack trace would be helpful.

Or let's try again with 133 once it has a stable release.

**Comment by Plajer** [comment]
The stack trace is:
```
[vike@0.4.204][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    createErrorWithCleanStackTrace createErrorWithCleanStackTrace.js:4
    assert assert.js:54
    getState history.js:53
    saveScrollPosition history.js:69
    onPageHide onPageVisibilityChange.js:6
    onPageHide onPageVisibilityChange.js:4
    autoSaveScrollPosition setScrollPosition.js:94
    initHistoryAndScroll initClientRouter.js:34
    initClientRouter initClientRouter.js:12
    <anonymous> entry.js:10
```

**Comment by brillout** [comment]
Hm, seems like a similar issue where Firefox erroneously sets `history.state` to `null`.

I added some debug logs. Let's further dig if we can reproduce on a stable Firefox version.
